framework:
    messenger:
        failure_transport: failed

        transports:
            async: doctrine://default
            failed: doctrine://default?queue_name=failed

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: ~

        routing:
            App\Message\SendTelegramNotification: async
